appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Zq3ofPZSpKvwcners46nkKBKf3GHdTYtitaf36+2CFZeYeq+ihZ1Tr8aFJpgY3LxzJSn+vU1EWIL8o/0nn2nIZkm5CRpkg+qtmHqdmzpzYCLlBYCLluNEntdsjQCLjjgu7v84OmX3g0WgAMhsSjlmeC2o0GIYWjmVzloDt++kfawYQJMnhVP9wEIj16IxXN6XeOjqXF+8jm0Fmh/YVe2zYMzA25pL/nxZruaxZbkpfFbUuAtuHy+Bg+3R9Wl86PKAqgxHvEAZhMRtQrzVwQK2ydGhxx4vduoWyEx12bzzlWly7f+KPGOVk8FkG654Ws128HkL5y0qWmaB231qEfFNnSGdElOI2TNvnqxxukEemstonFAvLSziQpXCYTqzbhWe4EayzU5rY1mIgsmYmTcEhmVoviaV6lXsbdP8kcBgi5z58bYfVlULSCV/M4HfiWSb9YRrx7Pn0nG96xscKr7491sIAVThvnPBmpkgbVqPOOhfkYpuFseM7Am9/viHLyOy22spI0xgbVIXZJo434ZaSJCBkAft57VD/j4zbBGDUCKyFdLNIsNmRwNcECoHnLTjAAdUIlmD631m+jo3RIsCUvRTi6rtQRRrcr6XrTIiYKf/jVunBDH53YVemzSy8B8NjvacWvwasHiAboKC0y5nlvuxv56TwHh37Vy60e8viU=
conda_forge_output_validation: false
